### PR TITLE
add load test for amd; clean up tests folder

### PR DESCRIPTION
**Pull request by Neil-Ni**
Hey Jason, my pleasure to help out. And thank you so much for coming up with this project. this is exactly what I was looking for : )

a few changes in this PR:
 - add require js to test amd
 - clean up tests structure

Any chance you could bump the release to bower after this :)?

thanks, -Neil

### CODE REVIEW

**Comment by jasonzissman** [comment]
Looks good!  I merged in the PR.  I'll tweak a few things in the project tonight and then push to Bower shortly after.

**Comment by jasonzissman** [comment]
Thanks again!

**Comment by jasonzissman** [comment]
And I released 1.2.0, it appears to be in Bower.  Let me know if any issues arise.

**Comment by Neil-Ni** [comment]
works perfectly. Thanks for the quick update! :)

**Pull request merged**
